### ISSUE TITLE
Unable to select source files

### ISSUE THREAD

**Issue by ZhongBaode** [cardboardcode/dbs_autodoc#1]
Hi, currently using the dbs_autodoc and I am having difficulty using the GUI. When I try to select source file, it would only allow me open folders instead of selecting it, thus I am unable to select a folder as the only option is to open it.

I had git cloned the repo into my /home folder and ran the commands from the tutorial in there

**Comment by cardboardcode** [comment]
@ZhongBaode Sorry for the late reply.

Closing due to staleness. Feel free to open if there is still a need to address the issue.
